ci: workaround godot headless segfault on exit

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -41,7 +41,15 @@ jobs:
         run: mkdir -v -p build/windows
 
       - name: Export Windows
-        run: godot --headless --export-release "Windows Desktop" build/windows/$EXPORT_NAME.exe
+        run: |
+          godot --headless --export-release "Windows Desktop" build/windows/$EXPORT_NAME.exe || true
+          if [ -f "build/windows/$EXPORT_NAME.exe" ]; then
+            echo "Export successful: Artifact found."
+            exit 0
+          else
+            echo "Export failed: Artifact not found."
+            exit 1
+          fi
 
       - name: Upload Artifact
         uses: actions/upload-artifact@v4
@@ -78,7 +86,15 @@ jobs:
         run: mkdir -v -p build/macos
 
       - name: Export macOS
-        run: godot --headless --export-release "macOS" build/macos/$EXPORT_NAME.zip
+        run: |
+          godot --headless --export-release "macOS" build/macos/$EXPORT_NAME.zip || true
+          if [ -f "build/macos/$EXPORT_NAME.zip" ]; then
+            echo "Export successful: Artifact found."
+            exit 0
+          else
+            echo "Export failed: Artifact not found."
+            exit 1
+          fi
 
       - name: Upload Artifact
         uses: actions/upload-artifact@v4
